package com.leonardorozza.mvgrreparacionesbackend.persistence.entity.enums;

public enum TipoDocumentoLegal {
    TERMINOS_SERVICIO,
    POLITICA_PRIVACIDAD,
    ACUERDO_TRATAMIENTO_DATOS,
    CONDICIONES_PRO,
    POLITICA_CANCELACIONES_REEMBOLSOS,
    POLITICA_CIERRE_CUENTA,
    AVISO_CLIENTES_TALLER,
    TERMINOS_USUARIO,
    AVISO_PRIVACIDAD_USUARIO,
    COMPROMISO_CONFIDENCIALIDAD,
    ATESTACION_DATOS_CLIENTE
}
