-- ============================================================
-- V10 - Cobros (pagos sobre reparaciones)
-- ============================================================
CREATE TABLE cobros (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reparacion_id BIGINT        NOT NULL REFERENCES reparaciones (id) ON DELETE CASCADE,
    taller_id     BIGINT        NOT NULL REFERENCES talleres (id),
    monto         NUMERIC(10,2) NOT NULL,
    metodo        VARCHAR(20)   NOT NULL,
    observaciones VARCHAR(255),
    created_at    TIMESTAMP
);
CREATE INDEX idx_cobros_reparacion ON cobros (reparacion_id);
CREATE INDEX idx_cobros_taller ON cobros (taller_id);
CREATE INDEX idx_cobros_taller_fecha ON cobros (taller_id, created_at);
