-- Estado actual de Mercado Pago sin perder los campos compatibles existentes.
ALTER TABLE suscripciones ADD COLUMN mp_status VARCHAR(50);
ALTER TABLE suscripciones ADD COLUMN mp_external_reference VARCHAR(255);
ALTER TABLE suscripciones ADD COLUMN mp_checkout_init_point VARCHAR(1000);
ALTER TABLE suscripciones ADD COLUMN mp_next_payment_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE suscripciones ADD COLUMN mp_last_payment_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE suscripciones ADD COLUMN mp_last_authorized_payment_id VARCHAR(255);

CREATE UNIQUE INDEX uk_suscripciones_mp_external_reference
    ON suscripciones (mp_external_reference)
    WHERE mp_external_reference IS NOT NULL;

-- Historial de vínculos externos. Un nuevo checkout archiva el anterior, no lo borra.
CREATE TABLE subscription_provider_links (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suscripcion_id           BIGINT       NOT NULL,
    provider                 VARCHAR(40)  NOT NULL,
    external_subscription_id VARCHAR(255),
    external_reference       VARCHAR(255) NOT NULL,
    idempotency_key          VARCHAR(80)  NOT NULL,
    checkout_url             VARCHAR(1000),
    status                   VARCHAR(50),
    is_current               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    last_reconciled_at       TIMESTAMP WITH TIME ZONE,
    last_reconciliation_status VARCHAR(30),
    last_reconciliation_error  VARCHAR(500),
    CONSTRAINT fk_provider_link_suscripcion
        FOREIGN KEY (suscripcion_id) REFERENCES suscripciones (id) ON DELETE RESTRICT,
    CONSTRAINT uk_subscription_provider_external_id
        UNIQUE (provider, external_subscription_id),
    CONSTRAINT uk_subscription_provider_external_ref
        UNIQUE (provider, external_reference),
    CONSTRAINT uk_subscription_provider_idempotency
        UNIQUE (provider, idempotency_key)
);

CREATE INDEX idx_subscription_provider_current
    ON subscription_provider_links (suscripcion_id, is_current);

-- Inbox durable: permite deduplicar, auditar y reintentar sin conservar payload sensible.
CREATE TABLE payment_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider           VARCHAR(40)  NOT NULL,
    provider_event_key VARCHAR(255) NOT NULL,
    request_id         VARCHAR(255),
    event_type         VARCHAR(100) NOT NULL,
    data_id            VARCHAR(255) NOT NULL,
    status             VARCHAR(30)  NOT NULL,
    attempts           INTEGER      NOT NULL,
    received_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    last_attempt_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at       TIMESTAMP WITH TIME ZONE,
    last_error         VARCHAR(500),
    CONSTRAINT uk_payment_event_provider_key UNIQUE (provider, provider_event_key)
);

CREATE INDEX idx_payment_events_retry ON payment_events (status, attempts, received_at);

-- Libro local de facturas/cobros recurrentes informados por Mercado Pago.
CREATE TABLE subscription_payments (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suscripcion_id                 BIGINT         NOT NULL,
    provider                       VARCHAR(40)    NOT NULL,
    external_authorized_payment_id VARCHAR(255)   NOT NULL,
    external_payment_id            VARCHAR(255),
    amount                         NUMERIC(19, 2) NOT NULL,
    currency                       VARCHAR(3)     NOT NULL,
    invoice_status                 VARCHAR(50),
    payment_status                 VARCHAR(50),
    status_detail                  VARCHAR(100),
    summarized                     VARCHAR(50),
    retry_attempt                  INTEGER,
    debit_at                       TIMESTAMP WITH TIME ZONE,
    provider_created_at            TIMESTAMP WITH TIME ZONE,
    provider_modified_at           TIMESTAMP WITH TIME ZONE,
    created_at                     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_subscription_payment_suscripcion
        FOREIGN KEY (suscripcion_id) REFERENCES suscripciones (id) ON DELETE RESTRICT,
    CONSTRAINT uk_subscription_payment_provider_id
        UNIQUE (provider, external_authorized_payment_id)
);

CREATE INDEX idx_subscription_payments_suscripcion
    ON subscription_payments (suscripcion_id, debit_at);
