-- ============================================================
-- V1 - Esquema inicial: MVGR Reparaciones
-- ============================================================

-- ------------------------------------------------------------
-- USUARIOS (autenticación)
-- ------------------------------------------------------------
CREATE TABLE users (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255) UNIQUE,
    role     VARCHAR(255) NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ------------------------------------------------------------
-- CLIENTES
-- ------------------------------------------------------------
CREATE TABLE clientes (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(60)  NOT NULL,
    apellido  VARCHAR(60)  NOT NULL,
    telefono  VARCHAR(20)  NOT NULL UNIQUE,
    email     VARCHAR(120) UNIQUE,
    direccion VARCHAR(255)
);

-- ------------------------------------------------------------
-- EQUIPOS (pertenecen a un cliente)
-- ------------------------------------------------------------
CREATE TABLE equipos (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca       VARCHAR(60) NOT NULL,
    modelo      VARCHAR(60) NOT NULL,
    imei        VARCHAR(30),
    color       VARCHAR(40),
    descripcion VARCHAR(255),
    cliente_id  BIGINT      NOT NULL REFERENCES clientes (id)
);

-- ------------------------------------------------------------
-- REPARACIONES (pertenecen a un equipo)
-- ------------------------------------------------------------
CREATE TABLE reparaciones (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_problema   VARCHAR(255)  NOT NULL,
    estado                 VARCHAR(30)   NOT NULL,
    precio_estimado        NUMERIC(10, 2),
    precio_final           NUMERIC(10, 2),
    fecha_ingreso          DATE,
    fecha_estimada_entrega DATE,
    fecha_entrega          DATE,
    equipo_id              BIGINT        NOT NULL REFERENCES equipos (id)
);

-- ------------------------------------------------------------
-- REPUESTOS (opcionalmente asociados a una reparación)
-- ------------------------------------------------------------
CREATE TABLE repuestos (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(80)   NOT NULL,
    descripcion   VARCHAR(255),
    precio        NUMERIC(10, 2) NOT NULL,
    reparacion_id BIGINT        REFERENCES reparaciones (id)
);

-- ------------------------------------------------------------
-- ÍNDICES sobre las claves foráneas y búsquedas frecuentes
-- ------------------------------------------------------------
CREATE INDEX idx_equipos_cliente        ON equipos (cliente_id);
CREATE INDEX idx_reparaciones_equipo    ON reparaciones (equipo_id);
CREATE INDEX idx_reparaciones_estado    ON reparaciones (estado);
CREATE INDEX idx_repuestos_reparacion   ON repuestos (reparacion_id);
