-- ============================================================
-- V2 - Multi-tenancy (talleres) + suscripciones
-- ============================================================

-- ------------------------------------------------------------
-- TALLERES (tenants)
-- ------------------------------------------------------------
CREATE TABLE talleres (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(120) NOT NULL,
    email_contacto VARCHAR(120),
    telefono       VARCHAR(20),
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);

-- ------------------------------------------------------------
-- SUSCRIPCIONES (una por taller)
-- ------------------------------------------------------------
CREATE TABLE suscripciones (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taller_id         BIGINT      NOT NULL UNIQUE REFERENCES talleres (id),
    plan              VARCHAR(30) NOT NULL,
    estado            VARCHAR(30) NOT NULL,
    fecha_inicio      DATE,
    fecha_fin_trial   DATE,
    proximo_cobro     DATE,
    mp_preapproval_id VARCHAR(255),
    mp_payer_id       VARCHAR(255),
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE INDEX idx_suscripciones_preapproval ON suscripciones (mp_preapproval_id);

-- ------------------------------------------------------------
-- taller_id en las tablas existentes (nullable por ahora;
-- se hará NOT NULL en una migración posterior, una vez backfilleado)
-- ------------------------------------------------------------
ALTER TABLE users        ADD COLUMN taller_id BIGINT REFERENCES talleres (id);
ALTER TABLE clientes     ADD COLUMN taller_id BIGINT REFERENCES talleres (id);
ALTER TABLE equipos      ADD COLUMN taller_id BIGINT REFERENCES talleres (id);
ALTER TABLE reparaciones ADD COLUMN taller_id BIGINT REFERENCES talleres (id);
ALTER TABLE repuestos    ADD COLUMN taller_id BIGINT REFERENCES talleres (id);

CREATE INDEX idx_users_taller        ON users (taller_id);
CREATE INDEX idx_clientes_taller     ON clientes (taller_id);
CREATE INDEX idx_equipos_taller      ON equipos (taller_id);
CREATE INDEX idx_reparaciones_taller ON reparaciones (taller_id);
CREATE INDEX idx_repuestos_taller    ON repuestos (taller_id);
