-- ============================================================
-- V8 - Presupuestos por reparación (con aprobación del cliente)
-- ============================================================
CREATE TABLE presupuestos (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reparacion_id  BIGINT        NOT NULL REFERENCES reparaciones (id) ON DELETE CASCADE,
    taller_id      BIGINT        NOT NULL REFERENCES talleres (id),
    estado         VARCHAR(20)   NOT NULL,
    total          NUMERIC(10,2) NOT NULL DEFAULT 0,
    observaciones  VARCHAR(1000),
    fecha_respuesta TIMESTAMP,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);
CREATE INDEX idx_presupuestos_reparacion ON presupuestos (reparacion_id);
CREATE INDEX idx_presupuestos_taller ON presupuestos (taller_id);

CREATE TABLE presupuesto_items (
    presupuesto_id  BIGINT        NOT NULL REFERENCES presupuestos (id) ON DELETE CASCADE,
    descripcion     VARCHAR(255)  NOT NULL,
    cantidad        INT           NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL
);
CREATE INDEX idx_presupuesto_items_presupuesto ON presupuesto_items (presupuesto_id);
