-- ============================================================
-- V9 - Inventario de artículos (catálogo con stock)
-- ============================================================
CREATE TABLE articulos (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taller_id    BIGINT        NOT NULL REFERENCES talleres (id),
    nombre       VARCHAR(120)  NOT NULL,
    descripcion  VARCHAR(255),
    sku          VARCHAR(60),
    precio       NUMERIC(10,2) NOT NULL DEFAULT 0,
    costo        NUMERIC(10,2),
    stock        INT           NOT NULL DEFAULT 0,
    stock_minimo INT           NOT NULL DEFAULT 0,
    activo       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP
);
CREATE INDEX idx_articulos_taller ON articulos (taller_id);

-- Enlace opcional de un repuesto usado en una reparación con un artículo del inventario
ALTER TABLE repuestos ADD COLUMN articulo_id BIGINT REFERENCES articulos (id);
ALTER TABLE repuestos ADD COLUMN cantidad    INT NOT NULL DEFAULT 1;
CREATE INDEX idx_repuestos_articulo ON repuestos (articulo_id);
